steps:
# Debugging
- name: 'alpine'
  args: ['echo', "hello ${_IMAGE_NAME_FULL}"]
# Uses the docker build step to build an image
- name: 'gcr.io/cloud-builders/docker'
  args: [ "build", "-t", "${_IMAGE_NAME_FULL}:${_TAG}", "-t", "${_IMAGE_NAME_FULL}:latest", "." ]
  dir: "app/streamlit-app"
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', "${_IMAGE_NAME_FULL}:latest"]
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ["run", "deploy", "streamlit-app-v2", "--image", "${_IMAGE_NAME_FULL}:latest", "--region", "${_LOCATION}", "--set-env-vars", "VESPA_ENDPOINT=http://34.41.66.135:80", "--allow-unauthenticated", "--memory", "4Gi"]

# Push the image to Container Registry
images:
- '${_IMAGE_NAME_FULL}:${_TAG}'
- '${_IMAGE_NAME_FULL}:latest'

substitutions:
    _LOCATION: "us-central1"
    _GCLOUD_ARTIFACTS_REPOSITORY: 'prefect'
    _IMAGE_NAME: 'streamlit-app'
    _TAG: "${COMMIT_SHA}"
    _IMAGE_NAME_FULL: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_GCLOUD_ARTIFACTS_REPOSITORY}/${_IMAGE_NAME}'
options:
    dynamic_substitutions: true

# https://github.com/GoogleCloudPlatform/cloud-build-samples/blob/main/run-example-builddeploy/cloudbuild.yaml
